<a href="https://colab.research.google.com/github/soumensen411/Job-Postings-EDA-with-Pandas/blob/main/pandas_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

# 🟢 Beginner Q1. Basic Loading & Inspection Load the CSV into a DataFrame and display the first 10 rows. How many rows and columns does the dataset have? List all column names and their data types.

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Data Science/pandas exercise/LinkedIn_RDB_three.csv')

In [4]:
df.head(10) # first 10 rows

,job_id,title,description,pay_period,work_type,job_location,applies,remote_allowed,views,level,sponsored,compensation,job_domain,company_id,ben_pack_id
0,903408693,Office Associate,Provide clerical and administrative support to...,YEARLY,Full-time,"Albany, GA",5,False,49,NaN,True,"$42,000.00",Administration,3894635,1.0
1,1029078768,Registered Nurse (RN) Vaccinator,United Staffing Solutions is partnering with o...,HOURLY,Part-time,"Muskegon, MI",0,False,4,NaN,False,"$104,000.00",Healthcare,61469,1.0
2,1657978824,"REMOTE STEEL BUILDING SALES MAKE $1,000 TO $30...","REMOTE WORK FROM HOME $1,000 TO $10,000 COMMIS...",MONTHLY,Contract,"Texas, United States",0,True,0,NaN,False,"$144,000.00",Other,89350959,1.0
3,2148434033,Contract Bilingual Recruiter,"Location: Phoenix, AZ 85006---- IN OFFICE JOB ...",YEARLY,Contract,"Phoenix, AZ",0,False,0,Associate,False,"$65,000.00",Human Resources,1082195,1.0
4,2148434586,"Manager, Salesforce Platform",Invitation Homes is a fast-paced evolving publ...,YEARLY,Full-time,"New Hampshire, United States",0,False,0,Mid-Senior level,False,"$170,976.00",Information Technology,2780388,113.0
5,2148434616,"Lead Solar Maintenance Roofer, Residential Ser...",What to Expect\n The Lead Service Installer wi...,HOURLY,Full-time,"San Diego, CA",0,False,0,Mid-Senior level,False,"$95,680.00",Management,15564,152.0
6,2148434725,Mental Health Professional,"You Belong Here.\nAt MultiCare, we strive to o...",YEARLY,Full-time,"Spokane, WA",0,False,0,Entry level,False,"$79,541.00",Healthcare,13074,1.0
7,2148434726,Mental Health Professional,"You Belong Here.\nAt MultiCare, we strive to o...",YEARLY,Full-time,"Spokane, WA",0,False,0,Entry level,False,"$79,541.00",Healthcare,13074,1.0
8,2148434909,Clinic Managers - Physical Therapist,Salary Range: Highly Competitive! - Salary Ran...,YEARLY,Full-time,"Puyallup, WA",0,False,0,Mid-Senior level,False,"$117,510.65",Healthcare,6600327,1.0
9,2282679989,Paid Intern - Unscripted Development,"We are seeking smart, motivated interns for th...",HOURLY,Internship,"Los Angeles, CA",0,False,70,NaN,False,"$41,600.00",Education,21514196,1.0

In [5]:
df.shape # our dataset has 6328 rows and 15 columns

(6328, 15)

In [6]:
df.info() # column names and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   object
 2   description     6328 non-null   object
 3   pay_period      6328 non-null   object
 4   work_type       6328 non-null   object
 5   job_location    6328 non-null   object
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int64
 9   level           4520 non-null   object
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   object
 12  job_domain      6205 non-null   object
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float64(1), int64(4), object(8)
memory usage: 655.2+ KB

# 2. Q2. Missing Values Find the number of missing values in each column. Which column has the most nulls? Drop all rows where both compensation and level are missing, and report how many rows remain.

In [7]:
df.isnull().sum() # missing values in each column.

job_id               0
title                0
description          0
pay_period           0
work_type            0
job_location         0
applies              0
remote_allowed       0
views                0
level             1808
sponsored            0
compensation         0
job_domain         123
company_id           0
ben_pack_id          1
dtype: int64

In [8]:
df.isnull().sum().idxmax() # Which column has the most nulls?

'level'

In [9]:
df = df.dropna(subset = ['compensation','level']) # Drop all rows where both compensation and level are missing

In [10]:
df.shape

(4520, 15)

# 3. Q3. Filtering Filter the dataset to show only full-time, remote-allowed jobs. How many such jobs exist?

In [11]:
df['work_type'].unique()

array(['Contract', 'Full-time', 'Temporary', 'Part-time', 'Other',
       'Internship'], dtype=object)

In [12]:
df[df['work_type'] == 'Full-time'] # only full-time job description

,job_id,title,description,pay_period,work_type,job_location,applies,remote_allowed,views,level,sponsored,compensation,job_domain,company_id,ben_pack_id
4,2148434586,"Manager, Salesforce Platform",Invitation Homes is a fast-paced evolving publ...,YEARLY,Full-time,"New Hampshire, United States",0,False,0,Mid-Senior level,False,"$170,976.00",Information Technology,2780388,113.0
5,2148434616,"Lead Solar Maintenance Roofer, Residential Ser...",What to Expect\n The Lead Service Installer wi...,HOURLY,Full-time,"San Diego, CA",0,False,0,Mid-Senior level,False,"$95,680.00",Management,15564,152.0
6,2148434725,Mental Health Professional,"You Belong Here.\nAt MultiCare, we strive to o...",YEARLY,Full-time,"Spokane, WA",0,False,0,Entry level,False,"$79,541.00",Healthcare,13074,1.0
7,2148434726,Mental Health Professional,"You Belong Here.\nAt MultiCare, we strive to o...",YEARLY,Full-time,"Spokane, WA",0,False,0,Entry level,False,"$79,541.00",Healthcare,13074,1.0
8,2148434909,Clinic Managers - Physical Therapist,Salary Range: Highly Competitive! - Salary Ran...,YEARLY,Full-time,"Puyallup, WA",0,False,0,Mid-Senior level,False,"$117,510.65",Healthcare,6600327,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6322,3701373383,Senior Analyst,About Us\nMarketAxess is on a journey to digit...,YEARLY,Full-time,"New York, NY",14,False,79,Mid-Senior level,False,"$85,000.00",Business Development,13651,49.0
6323,3701373385,Sales Manager,"Sales ManagerTexas, US $60,000–$70,000OTE $250...",YEARLY,Full-time,"Texas, United States",7,True,56,Mid-Senior level,False,"$70,000.00",Business Development,18312164,1.0
6325,3701373432,Continuous Improvement Specialist,Continuous Improvement Specialist Opportunity!...,YEARLY,Full-time,"Mississippi, United States",11,False,28,Mid-Senior level,True,"$200,000.00",Management,2121817,128.0
6326,3701373493,Sr. Bilingual Copywriter (Canadian French),Overview\nTHE ROLE:\nThe Senior Bilingual Copy...,YEARLY,Full-time,"Torrance, CA",4,False,29,Mid-Senior level,False,"$105,200.00",Marketing,5619,47.0
6327,3701373524,MRI Manager,Grade 105\nJob Type: Officer of Administration...,YEARLY,Full-time,"New York, NY",0,False,10,Mid-Senior level,False,"$135,000.00",Other,2623,NaN

In [13]:
df[df['work_type'] == 'Full-time'].value_counts().sum() # total full-time jobs

np.int64(3744)

# Q4. Value Counts & Grouping What are the top 5 most common job_domain values? For each domain, calculate the average number of views and average number of applies.

In [14]:

top_5_job_domains = df['job_domain'].value_counts().head().index.tolist() # the top 5 most common job_domain values
print("top 5 most comon job_domain are : ", top_5_job_domains)

top 5 most comon job_domain are :  ['Management', 'Information Technology', 'Sales', 'Engineering', 'Other']

In [15]:

df_top_domains = df[df['job_domain'].isin(top_5_job_domains)]
avg_values = df_top_domains.groupby('job_domain')[['views','applies']].mean()
print(avg_values)

                             views    applies
job_domain
Engineering             103.149510  23.933824
Information Technology  127.556044  31.105495
Management               37.808621   5.756897
Other                    32.809896   4.986979
Sales                    42.955056   9.233708

# Q5. String Cleaning The compensation column contains values like "$42,000.00 ". Convert it to a numeric column (float). Then find the median compensation for each pay_period type (YEARLY, HOURLY, MONTHLY).

In [16]:
df['compensation']

3        $65,000.00
4       $170,976.00
5        $95,680.00
6        $79,541.00
7        $79,541.00
            ...
6323     $70,000.00
6324     $49,691.20
6325    $200,000.00
6326    $105,200.00
6327    $135,000.00
Name: compensation, Length: 4520, dtype: object

In [17]:
df['compensation'] = df['compensation'].str.replace(r'[$,]', '', regex=True).astype(float) # remove the $ symbol

In [18]:
df['pay_period'].unique()

array(['YEARLY', 'HOURLY', 'MONTHLY'], dtype=object)

In [19]:
df['compensation'].groupby(df['pay_period']).median()

pay_period
HOURLY      58240.00
MONTHLY     67759.98
YEARLY     120000.00
Name: compensation, dtype: float64

# # Q6. Sorting & Ranking Find the top 10 job titles with the highest views. Among these, how many are sponsored vs. non-sponsored?

In [20]:
top_views_index = df.sort_values(by='views',ascending=False).head(10)
top_views_index[['title','views']]  # the top 10 job titles with the highest views.

                                                 title  views
336                    Customer Service Representative   2478
727             Manager, Workforce Management (Remote)   2177
5942                       Business Operations Manager   2131
601                    Director of Engineering, Growth   1555
5163                    Industry Operations Consultant   1550
5517                              Healthcare Recruiter   1502
5627                          Field Operations Manager   1481
751   Senior Manager, Sales Enablement and Development   1403
2076                        Payment Posting Specialist   1383
420                                   Digital Producer   1382

# Q7. GroupBy + Aggregation Group jobs by work_type and compute: 1. Total number of jobs 2. Mean applies 3. Max views

In [26]:
df.groupby('work_type').agg({"job_id":"count","applies":"mean","views":'max'})

            job_id    applies  views
work_type
Contract       536  30.264925   2478
Full-time     3745  14.784780   2177
Internship      11   9.818182    141
Other           16   2.625000    151
Part-time      178   2.185393    377
Temporary       34  27.294118   2131

# Q8. Pivot Table Create a pivot table showing the average compensation for each combination of work_type (rows) and pay_period (columns). Which combination has the highest average compensation?

In [30]:
df.pivot_table(index = 'work_type',
               columns='pay_period',
               values='compensation',
               aggfunc='mean'
               )

pay_period         HOURLY        MONTHLY         YEARLY
work_type
Contract    101723.391481  121500.000000  101922.952381
Full-time    64551.752091   75523.648421  138803.175728
Internship   54264.600000  112080.000000  195905.000000
Other        77885.600000            NaN  133184.714286
Part-time    53370.474534   41360.000000  110802.750000
Temporary    71739.200000            NaN  126577.777778

# Q9. Apply & Lambda Using the job_location column, extract the state abbreviation (e.g., "Albany, GA" → "GA"). Add it as a new column called state. Then find the top 3 states by number of job postings.

In [34]:
df['state'] = df['job_location'].apply(
    lambda x : x.split(',')[-1].strip()  # extract the state abbreviation
)

,job_id,title,description,pay_period,work_type,job_location,applies,remote_allowed,views,level,sponsored,compensation,job_domain,company_id,ben_pack_id,demand,state
3,2148434033,Contract Bilingual Recruiter,"Location: Phoenix, AZ 85006---- IN OFFICE JOB ...",YEARLY,Contract,"Phoenix, AZ",0,False,0,Associate,False,65000.0,Human Resources,1082195,1.0,Low,AZ
4,2148434586,"Manager, Salesforce Platform",Invitation Homes is a fast-paced evolving publ...,YEARLY,Full-time,"New Hampshire, United States",0,False,0,Mid-Senior level,False,170976.0,Information Technology,2780388,113.0,Low,United States
5,2148434616,"Lead Solar Maintenance Roofer, Residential Ser...",What to Expect\n The Lead Service Installer wi...,HOURLY,Full-time,"San Diego, CA",0,False,0,Mid-Senior level,False,95680.0,Management,15564,152.0,Low,CA
6,2148434725,Mental Health Professional,"You Belong Here.\nAt MultiCare, we strive to o...",YEARLY,Full-time,"Spokane, WA",0,False,0,Entry level,False,79541.0,Healthcare,13074,1.0,Low,WA
7,2148434726,Mental Health Professional,"You Belong Here.\nAt MultiCare, we strive to o...",YEARLY,Full-time,"Spokane, WA",0,False,0,Entry level,False,79541.0,Healthcare,13074,1.0,Low,WA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6323,3701373385,Sales Manager,"Sales ManagerTexas, US $60,000–$70,000OTE $250...",YEARLY,Full-time,"Texas, United States",7,True,56,Mid-Senior level,False,70000.0,Business Development,18312164,1.0,Low,United States
6324,3701373427,Design Intern,Looking to redefine the skyline or to be a par...,HOURLY,Internship,"Miramar, FL",2,False,20,Mid-Senior level,False,49691.2,Design,1321042,1.0,Low,FL
6325,3701373432,Continuous Improvement Specialist,Continuous Improvement Specialist Opportunity!...,YEARLY,Full-time,"Mississippi, United States",11,False,28,Mid-Senior level,True,200000.0,Management,2121817,128.0,Low,United States
6326,3701373493,Sr. Bilingual Copywriter (Canadian French),Overview\nTHE ROLE:\nThe Senior Bilingual Copy...,YEARLY,Full-time,"Torrance, CA",4,False,29,Mid-Senior level,False,105200.0,Marketing,5619,47.0,Low,CA
6327,3701373524,MRI Manager,Grade 105\nJob Type: Officer of Administration...,YEARLY,Full-time,"New York, NY",0,False,10,Mid-Senior level,False,135000.0,Other,2623,NaN,Low,NY

In [35]:
df['demand'] = df['applies'].apply(
    lambda x : "High" if x>100 else 'Low'
)

In [39]:
df['state'].value_counts().head(3) # the top 3 states by number of job postings.

state
CA               901
United States    551
NY               328
Name: count, dtype: int64

# Q10. Correlation & Insight Is there a correlation between views and applies? Calculate the Pearson correlation coefficient. Then create a new column conversion_rate = applies / views (handle division by zero). Which job_domain has the highest average conversion rate?

In [40]:
df[['views','applies']].corr() # correlation between views and applies

            views   applies
views    1.000000  0.840699
applies  0.840699  1.000000

In [45]:
df['conversion_rate'] = df['applies'] / df['views'].replace(0, float('nan'))
df.groupby('job_domain')['conversion_rate'].mean().sort_values(ascending =False).head(1) # job_domain has the highest average conversion rate

job_domain
Training    0.245055
Name: conversion_rate, dtype: float64